---
#
# ____                          _____           _     
#/ ___|  ___ _ ____   _____ _ _|_   _|__   ___ | |___ 
#\___ \ / _ \ '__\ \ / / _ \ '__|| |/ _ \ / _ \| / __|
# ___) |  __/ |   \ V /  __/ |   | | (_) | (_) | \__ \
#|____/ \___|_|    \_/ \___|_|   |_|\___/ \___/|_|___/
#

# To reset the configuration to default, just delete it.
# It will be re-generated if you restart the Plugin or
# the Server.

# Do NOT change the 'version' or it will cause
# crashes!
version: 1.1.0-beta1

autoupdater:
 # Enable or disable the AutoUpdater
 # on Server start
 autoupdater: true
 # Preffered channel, which you want to use for the AutoUpdater
 # stable OR beta
 channel: stable
...
